/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--color-muted-foreground) / <alpha-value>)',
        card: 'rgb(var(--color-card) / <alpha-value>)',
        'card-foreground': 'rgb(var(--color-card-foreground) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',
        destructive: 'rgb(var(--color-destructive) / <alpha-value>)',
        'score-excellent': 'rgb(var(--color-score-excellent) / <alpha-value>)',
        'score-good': 'rgb(var(--color-score-good) / <alpha-value>)',
        'score-fair': 'rgb(var(--color-score-fair) / <alpha-value>)',
        'score-poor': 'rgb(var(--color-score-poor) / <alpha-value>)',
        'surface-raised': 'rgb(var(--color-surface-raised) / <alpha-value>)',
        hairline: 'rgb(var(--color-hairline) / <alpha-value>)',
        bar: 'rgb(var(--color-bar) / <alpha-value>)',
        'bar-icon': 'rgb(var(--color-bar-icon) / <alpha-value>)',
        'bar-active': 'rgb(var(--color-bar-active) / <alpha-value>)',
        'bar-icon-active': 'rgb(var(--color-bar-icon-active) / <alpha-value>)',
        'heat-empty': 'rgb(var(--color-heat-empty) / <alpha-value>)',
        'heat-0': 'rgb(var(--color-heat-0) / <alpha-value>)',
        'heat-1': 'rgb(var(--color-heat-1) / <alpha-value>)',
        'heat-2': 'rgb(var(--color-heat-2) / <alpha-value>)',
        'heat-3': 'rgb(var(--color-heat-3) / <alpha-value>)',
        'heat-4': 'rgb(var(--color-heat-4) / <alpha-value>)',
      },
    },
  },
  plugins: [],
};
