/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--color-muted-foreground) / <alpha-value>)',
        card: 'rgb(var(--color-card) / <alpha-value>)',
        'card-foreground': 'rgb(var(--color-card-foreground) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',
        destructive: 'rgb(var(--color-destructive) / <alpha-value>)',
        'score-excellent': 'rgb(var(--color-score-excellent) / <alpha-value>)',
        'score-good': 'rgb(var(--color-score-good) / <alpha-value>)',
        'score-fair': 'rgb(var(--color-score-fair) / <alpha-value>)',
        'score-poor': 'rgb(var(--color-score-poor) / <alpha-value>)',
        'surface-raised': 'rgb(var(--color-surface-raised) / <alpha-value>)',
        hairline: 'rgb(var(--color-hairline) / <alpha-value>)',
        bar: 'rgb(var(--color-bar) / <alpha-value>)',
        'bar-icon': 'rgb(var(--color-bar-icon) / <alpha-value>)',
        'bar-active': 'rgb(var(--color-bar-active) / <alpha-value>)',
        'bar-icon-active': 'rgb(var(--color-bar-icon-active) / <alpha-value>)',
        'heat-empty': 'rgb(var(--color-heat-empty) / <alpha-value>)',
        'heat-0': 'rgb(var(--color-heat-0) / <alpha-value>)',
        'heat-1': 'rgb(var(--color-heat-1) / <alpha-value>)',
        'heat-2': 'rgb(var(--color-heat-2) / <alpha-value>)',
        'heat-3': 'rgb(var(--color-heat-3) / <alpha-value>)',
        'heat-4': 'rgb(var(--color-heat-4) / <alpha-value>)',
        'sleep-heat-1': 'rgb(var(--color-sleep-heat-1) / <alpha-value>)',
        'sleep-heat-2': 'rgb(var(--color-sleep-heat-2) / <alpha-value>)',
        'sleep-heat-3': 'rgb(var(--color-sleep-heat-3) / <alpha-value>)',
        'sleep-heat-4': 'rgb(var(--color-sleep-heat-4) / <alpha-value>)',
        'metric-steps': 'rgb(var(--color-metric-steps) / <alpha-value>)',
        'metric-heart': 'rgb(var(--color-metric-heart) / <alpha-value>)',
        'metric-sleep': 'rgb(var(--color-metric-sleep) / <alpha-value>)',
        'metric-hrv': 'rgb(var(--color-metric-hrv) / <alpha-value>)',
        coach: 'rgb(var(--color-coach) / <alpha-value>)',
        'status-below': 'rgb(var(--color-status-below) / <alpha-value>)',
        'status-near': 'rgb(var(--color-status-near) / <alpha-value>)',
        'status-above': 'rgb(var(--color-status-above) / <alpha-value>)',
        'status-below-text': 'rgb(var(--color-status-below-text) / <alpha-value>)',
        'status-above-text': 'rgb(var(--color-status-above-text) / <alpha-value>)',
        'today-usual': 'rgb(var(--color-today-usual) / <alpha-value>)',
        'today-track': 'rgb(var(--color-today-track) / <alpha-value>)',
        'today-tick': 'rgb(var(--color-today-tick) / <alpha-value>)',
        tip: 'rgb(var(--color-tip) / <alpha-value>)',
        'tip-foreground': 'rgb(var(--color-tip-foreground) / <alpha-value>)',
      },
      // Family names must match FONTS in src/theme.ts (the expo-font keys).
      // ui/text.tsx swaps `sans` for the matching weight's family.
      fontFamily: {
        sans: ['Geist_400Regular'],
        display: ['InstrumentSerif_400Regular'],
      },
      // The type scale. Everything a screen needs is one of these, rather
      // than a one-off text-[13px]: eyebrow (small caps section labels),
      // the numeral sizes for scores and metrics, and the serif display sizes.
      fontSize: {
        eyebrow: ['11px', { lineHeight: '14px', letterSpacing: '1.4px' }],
        'numeral-sm': ['22px', { lineHeight: '26px', letterSpacing: '-0.5px' }],
        numeral: ['30px', { lineHeight: '34px', letterSpacing: '-1px' }],
        'numeral-lg': ['48px', { lineHeight: '52px', letterSpacing: '-1.8px' }],
        'numeral-xl': ['80px', { lineHeight: '84px', letterSpacing: '-3px' }],
        'display-sm': ['22px', { lineHeight: '28px' }],
        display: ['28px', { lineHeight: '32px' }],
        'display-lg': ['38px', { lineHeight: '42px' }],
      },
      borderRadius: {
        tile: '18px',
        card: '22px',
      },
    },
  },
  plugins: [],
};
