// Generates src/components/characters/sprites/data.ts from the approved design
// data in docs/design/pixel-coaches/cast.js. Rerun after editing the design.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';

const here = path.dirname(fileURLToPath(import.meta.url));
const src = readFileSync(path.join(here, '../../docs/design/pixel-coaches/cast.js'), 'utf8');
const ctx = {};
vm.runInNewContext(`${src}\nthis.CAST = CAST;`, ctx);
const SLIM = { luna: 0, mochi: 0, boba: 0, jelly: 0, sprout: 2 };
const out = Object.entries(ctx.CAST).map(([name, c]) => {
  const id = name.toLowerCase();
  const def = { half: c.grid, palette: c.pal, slim: SLIM[id] ?? 1 };
  for (const k of ['eyes', 'lid', 'shut', 'shift']) if (c[k] !== undefined) def[k] = c[k];
  return `  ${id}: ${JSON.stringify(def)},`;
});
writeFileSync(
  path.join(here, '../src/components/characters/sprites/data.ts'),
  `// GENERATED by scripts/port-sprites.mjs from docs/design/pixel-coaches/cast.js. Do not edit by hand.\n` +
    `import type { CharacterId } from '../types';\nimport type { SpriteDef } from './compose';\n\n` +
    `export const SPRITES: Record<CharacterId, SpriteDef> = {\n${out.join('\n')}\n};\n`,
);
console.log(`wrote ${out.length} sprites`);
